export const ActionType = {
  PASS: 'PASS',
  SWAP: 'SWAP',
  CHANGE_TURN: 'CHANGE_TURN',
  TURN_FACE_UP: 'TURN_FACE_UP',
  CLAIM_TOKEN: 'CLAIM_TOKEN',
  REPLACE_CARD: 'REPLACE_CARD'
}

export const AppMode = {
  START_STATE: 'START_STATE',
  GAME: 'GAME',
  PLAYER_WIN: 'PLAYER_WIN'
}

export const DrawType = {
  DECK: 'DECK',
  DISCARD: 'DISCARD'
}

export const MoveState = {
  START_STATE:  'START_STATE',
  CARD_DRAWN: 'CARD_DRAWN',
  DISCARD_CHOSEN: 'DISCARD_CHOSEN',
  TURN_FACE_UP_CHOSEN: 'TURN_FACE_UP_CHOSEN',
  TURN_FACE_UP_IN_PROGRESS: 'TURN_FACE_UP_IN_PROGRESS',
  SWAP_CHOSEN: 'SWAP_CHOSEN',
  SWAP_IN_PROGRESS: 'SWAP_IN_PROGRESS',
  PRE_END_STATE: 'PRE_END_STATE',
  CLAIMING_TOKEN: 'CLAIMING_TOKEN'
}

export const TokenType = {
  THREE_IN_A_ROW: 'THREE_IN_A_ROW',
  FOUR_IN_A_ROW: 'FOUR_IN_A_ROW',
  FIVE_IN_A_ROW: 'FIVE_IN_A_ROW',
  THREE_OF_A_KIND: 'THREE_OF_A_KIND',
  FULL_HOUSE: 'FULL_HOUSE'
}

export const CardValues = {
  WILD: 'WILD'
}
