export const MoveState = {
  START_STATE:  'START_STATE',
  CARD_DRAWN: 'CARD_DRAWN',
  DISCARD_CHOSEN: 'DISCARD_CHOSEN',
  CARD_DISCARDED: 'CARD_DISCARDED',
  SWAP_CHOSEN: 'SWAP_CHOSEN',
  SWAP_IN_PROGRESS: 'SWAP_IN_PROGRESS',
  PRE_END_STATE: 'PRE_END_STATE',
  CLAIMING_TOKEN: 'CLAIMING_TOKEN'
}

export const AppMode = {
  START_STATE: 'START_STATE',
  GAME: 'GAME',
  PLAYER_WIN: 'PLAYER_WIN'
}
